class State:

    IDLE_EVENT = 0
    RUN_LEFT_EVENT = 1
    RUN_RIGHT_EVENT = 2
    RUN_UP_EVENT = 3
    RUN_DOWN_EVENT = 4
    MOUSE_DIGESTION_LEFT_EVENT = 5
    MOUSE_DIGESTION_RIGHT_EVENT = 6
    MOUSE_CONSTIPATION_LEFT_EVENT = 7
    MOUSE_CONSTIPATION_RIGHT_EVENT = 8
    MOUSE_POOP_LEFT_EVENT = 9
    MOUSE_POOP_RIGHT_EVENT = 10
